export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    RESET_STATE:"RESET_STATE",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    SEARCH_PRODUCT:"SEARCH_PRODUCT",
    FILTER_PRODUCTS_BY_CATEGORY:"FILTER_PRODUCTS_BY_CATEGORY",
    FILTER_PRODUCTS_BY_RATING:"FILTER_PRODUCTS_BY_RATING",
    CLEAR_ALL_FILTERS: "CLEAR_ALL_FILTERS"
}